---
  - name: Remove any existing host keys
    delegate_to: localhost
    shell: |
      ssh-keygen -f "~/.ssh/known_hosts" -R "{{ansible_host}}"
    ignore_errors: yes
    when: 
      - hostvars[inventory_hostname].ansible_connection is not defined or (hostvars[inventory_hostname].ansible_connection is defined and hostvars[inventory_hostname].ansible_connection=='ssh')
  
  - name: get port, default 22
    delegate_to: localhost
    set_fact:
      ansible_ssh_port: "{{ hostvars[inventory_hostname]['ansible_ssh_port'] | default('22') }}"
    when: 
      - hostvars[inventory_hostname].ansible_connection is not defined or (hostvars[inventory_hostname].ansible_connection is defined and hostvars[inventory_hostname].ansible_connection=='ssh')

  - name: Ensure ssh host key known
    delegate_to: localhost
    lineinfile:
      dest: ~/.ssh/known_hosts
      create: yes
      state: present
      line: "{{ lookup('pipe', 'ssh-keyscan -trsa -p' + ansible_ssh_port + ' ' + ansible_host, errors='warn') }}"
    when: 
      - hostvars[inventory_hostname].ansible_connection is not defined or (hostvars[inventory_hostname].ansible_connection is defined and hostvars[inventory_hostname].ansible_connection=='ssh')