---
- name: Determine available groups
  getent:
    database: group
  register: getent_groups

- name: Determine available users
  getent:
    database: passwd
  register: getent_users

- name: Create a splunk group
  group:
    name: splunk
    state: present
  become: yes
  when:
    - getent_groups.ansible_facts.getent_group.splunk is not defined
    - groups.splunk is defined and inventory_hostname in groups['splunk']
    - (not groups.splunk_universal_forwarder is defined) or (groups.splunk_universal_forwarder is defined and not inventory_hostname in groups['splunk_universal_forwarder'])
  

- name: Create a splunk user
  user:
    name: splunk
    groups:                # Empty by default, here we give it some groups
      - splunk
    state: present
    shell: /bin/bash       # Defaults to /bin/bash
    expires: 1             # Expire Account
    system: true             # Defaults to no
    createhome: true        # Defaults to yes
    home: /home/splunk     # Defaults to /home/<username>
  become: yes
  when:
    - getent_groups.ansible_facts.getent_passwd.splunk is not defined
    - groups.splunk is defined and inventory_hostname in groups['splunk']
    - (not groups.splunk_universal_forwarder is defined) or (groups.splunk_universal_forwarder is defined and not inventory_hostname in groups['splunk_universal_forwarder'])
