---
- name: Update Splunk directory owner
  file:
    path: "{{ splunk.home }}"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
    recurse: yes
  become: yes
  when: groups.splunk is defined and inventory_hostname in groups['splunk'] and ((not groups.splunk_universal_forwarder is defined) or (groups.splunk_universal_forwarder is defined and not inventory_hostname in groups['splunk_universal_forwarder']))
