---
- name: Update Splunk directory owner
  file:
    path: "{{ splunk.home }}"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
    recurse: yes
  become: yes
  when: inventory_hostname in groups['splunk'] and not inventory_hostname in groups['splunk_universal_forwarder']