---
# splunk certs
- name: Creates splunk directory
  file:
    path: "{{ splunk_certs.splunk_certs_dir }}"
    state: directory
    recurse: true
  become: true
  when: groups.splunk is defined and inventory_hostname in groups['splunk'] and ((not groups.splunk_universal_forwarder is defined) or (groups.splunk_universal_forwarder is defined and not inventory_hostname in groups['splunk_universal_forwarder']))

- name: Copy splunk cert to server
  copy:
    src: "/tmp/{{ inventory_hostname }}.crt"
    dest: "{{ splunk_certs.splunk_certs_dir }}/splunk.crt"
  become: true
  when: groups.splunk is defined and inventory_hostname in groups['splunk'] and ((not groups.splunk_universal_forwarder is defined) or (groups.splunk_universal_forwarder is defined and not inventory_hostname in groups['splunk_universal_forwarder']))

- name: Copy splunk private key to server
  copy:
    src: "/tmp/{{ inventory_hostname }}.key"
    dest: "{{ splunk_certs.splunk_certs_dir }}/splunk.key"
  become: true
  when: groups.splunk is defined and inventory_hostname in groups['splunk'] and ((not groups.splunk_universal_forwarder is defined) or (groups.splunk_universal_forwarder is defined and not inventory_hostname in groups['splunk_universal_forwarder']))

- name: Copy splunk pem bundle to server
  copy:
    src: "/tmp/{{ inventory_hostname }}-bundle.pem"
    dest: "{{ splunk_certs.splunk_certs_dir }}/splunk.pem"
  become: true
  when: groups.splunk is defined and inventory_hostname in groups['splunk'] and ((not groups.splunk_universal_forwarder is defined) or (groups.splunk_universal_forwarder is defined and not inventory_hostname in groups['splunk_universal_forwarder']))

- name: Copy splunk pem bundle to server
  copy:
    src: "/tmp/{{ inventory_hostname }}-bundle.pem"
    dest: "{{ splunk_certs.splunk_certs_dir }}/../server.pem"
  become: true
  when: groups.splunk is defined and inventory_hostname in groups['splunk'] and ((not groups.splunk_universal_forwarder is defined) or (groups.splunk_universal_forwarder is defined and not inventory_hostname in groups['splunk_universal_forwarder']))

- name: Copy splunk ca cert pem to server
  copy:
    src: "/tmp/cacert.pem"
    dest: "{{ splunk_certs.splunk_certs_dir }}/cacert.pem"
  become: true
  when: groups.splunk is defined and inventory_hostname in groups['splunk'] and ((not groups.splunk_universal_forwarder is defined) or (groups.splunk_universal_forwarder is defined and not inventory_hostname in groups['splunk_universal_forwarder']))

- name: Copy ca cert pem to server
  copy:
    src: "/tmp/cacert.pem" 
    dest: "{{ splunk_certs.splunk_certs_dir }}/../cacert.pem"
  become: true
  when: groups.splunk is defined and inventory_hostname in groups['splunk'] and ((not groups.splunk_universal_forwarder is defined) or (groups.splunk_universal_forwarder is defined and not inventory_hostname in groups['splunk_universal_forwarder']))

- name: Restrict access to splunk cert material
  file:
    path: "{{ item }}"
    mode: '0400'
  with_items:
    - "{{ splunk_certs.splunk_certs_dir }}/splunk.crt"
    - "{{ splunk_certs.splunk_certs_dir }}/splunk.key"
    - "{{ splunk_certs.splunk_certs_dir }}/splunk.pem"
    - "{{ splunk_certs.splunk_certs_dir }}/cacert.pem"
    - "{{ splunk_certs.splunk_certs_dir }}/../cacert.pem"
    - "{{ splunk_certs.splunk_certs_dir }}/../server.pem"
  become: true
  when: groups.splunk is defined and inventory_hostname in groups['splunk'] and ((not groups.splunk_universal_forwarder is defined) or (groups.splunk_universal_forwarder is defined and not inventory_hostname in groups['splunk_universal_forwarder']))

# ansible awx cert
- name: Copy ansible cert to server
  copy:
    src: "/tmp/{{ inventory_hostname }}.crt"
    dest: "{{ ansible_certs.ansible_certs_dir }}/awx.crt"
  become: true
  when: groups.ansible is defined and inventory_hostname in groups['ansible']

- name: Copy splunk private key to server
  copy:
    src: "/tmp/{{ inventory_hostname }}.key"
    dest: "{{ ansible_certs.ansible_certs_dir }}/awx.key"
  become: true
  when: groups.ansible is defined and inventory_hostname in groups['ansible']

- name: Copy splunk pem bundle to server
  copy:
    src: "/tmp/{{ inventory_hostname }}-bundle.pem"
    dest: "{{ ansible_certs.ansible_certs_dir }}/awx.pem"
  become: true
  when: groups.ansible is defined and inventory_hostname in groups['ansible']

# install ca cert on linux
- name: Install ca package on rhel systems
  yum:
    name: ca-certificates
    state: present
  become: true
  when: ansible_os_family == "RedHat"

- name: install ca package on debian systems
  apt:
    name: ca-certificates
    state: present
    update_cache: yes
  become: true
  when: ansible_os_family == "Debian"

- name: Enable dynamic ca configuration on rhel6
  shell: /bin/update-ca-trust enable
  become: true
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 6

- name: Copy certificate authority to trusted ca path of the os
  copy:
    src: '{{ item }}'
    dest: '{{ ca_path[ansible_os_family][ansible_distribution_major_version|int] }}/'
    owner: root
    group: root
    mode: 0644
  with_items:
    - /tmp/cacert.pem
  notify:
    - update trusted ca debian
    - update trusted ca redhat
  become: true
