---
- name: Set local admin password
  win_user:
    name: Administrator
    password: "{{ windows_domain_controller_info['domain_admin_password'] }}"
    state: present

- name: Setting DNS Servers
  win_dns_client:
    adapter_names: "*"
    ipv4_addresses: "{{ windows_domain_info['dns_servers'] }}"

# wait for dns change before attempting to join the domain
- name: Wait for connection after DNS update
  wait_for_connection:
    timeout: 900
    delay: 30

- name: Join to the domain
  win_domain_membership:
    dns_domain_name: "{{ windows_domain_controller_info['dns_domain_name'] }}"
    domain_admin_user: "{{ windows_domain_controller_info['domain_admin_user'] }}"
    domain_admin_password: "{{ windows_domain_controller_info['domain_admin_password'] }}"
    state: domain
  register: domain_state

- name: Reboot to complete domain membership setup
  win_reboot:
    shutdown_timeout: 600
    reboot_timeout: 600
    post_reboot_delay: 300
  when: domain_state.reboot_required