---
- name: Set local admin password
  win_user:
    name: Administrator
    password: "{{ windows_domain_controller_info['domain_admin_password'] }}"
    state: present

- name: Setting DNS Servers
  win_dns_client:
    adapter_names: "*"
    ipv4_addresses: "{{ windows_domain_info['dns_servers'] }}"

- name: Wait for domain fqdn resolution
  win_shell: |
    start-sleep -Seconds 5
    while($true){
      try {
          [Net.DNS]::GetHostEntry("{{ windows_domain_controller_info['dns_domain_name'] }}")
          write-output "DNS Resolution Success"
          break;
      }catch{
          write-output "DNS Resolution Failure"
      }
      start-sleep -Seconds 5
    }
  async: 900
  poll: 5
  register: async_out

- name: 'DNS - check on async task'
  async_status:
    jid: "{{ async_out.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 30

- name: Join to the domain
  win_domain_membership:
    dns_domain_name: "{{ windows_domain_controller_info['dns_domain_name'] }}"
    domain_admin_user: "{{ windows_domain_controller_info['domain_admin_user'] }}"
    domain_admin_password: "{{ windows_domain_controller_info['domain_admin_password'] }}"
    state: domain
  register: domain_state
  retries: 10
  delay: 30

- name: Reboot to complete domain membership setup
  win_reboot:
    pre_reboot_delay: 120
    reboot_timeout: 600
    post_reboot_delay: 120
  when: domain_state.reboot_required