---    
    # required for win_dsc
    - name: Verify the WSMan HTTP listener is active and configured correctly
      win_shell: |
        # basic auth required for DC promotion as all other auth types fail (https://github.com/ansible/ansible/issues/39235)
        Set-Item -Path WSMan:\localhost\Service\Auth\Basic -Value $true
        
        $port = (Get-Item -LiteralPath WSMan:\localhost\Client\DefaultPorts\HTTP).Value
        $onlinePorts = @(Get-ChildItem -LiteralPath WSMan:\localhost\Listener |
            Where-Object { 'Transport=HTTP' -in $_.Keys } |
            Get-ChildItem |
            Where-Object Name -eq Port |
            Select-Object -ExpandProperty Value)

        if ($port -notin $onlinePorts) {
            Write-Output "Adding required HTTP listener"
            Enable-PSRemoting -Force

            
        }