---
  - include: powershell-strong-crypto.yml
    when: ansible_distribution is search ('Microsoft')
  - include: install-packageprovider-nuget.yml
    when: ansible_distribution is search ('Microsoft')
  - include: add-psgallery-trusted-repo.yml
    when: ansible_distribution is search ('Microsoft')
  - include: ensure-winrm-http-listener.yml
    when: ansible_distribution is search ('Microsoft')
  - include: chocolately-components.yml
    when: 
      - ansible_distribution is search ('Microsoft')
      - groups.win10 is defined and inventory_hostname in groups['win10']
  - include: set-explorer-options.yml
    when: ansible_distribution is search ('Microsoft')
  #- include: disable-windows-defender.yml
  #  when: ansible_distribution is search ('Microsoft')
  #- include: install-visual-c++.yml
  #  when: ansible_distribution is search ('Microsoft')