---
  - name: Update explorer settings
    win_shell: |
      reg load HKLM\DefaultUser C:\Users\Default\NTUSER.DAT
      $path = "HKLM:\Defaultuser\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"
      New-ItemProperty -Path $path -Name HideFileExt -Value "0" -PropertyType DWord
      New-ItemProperty -Path $path -Name Hidden -Value "1" -PropertyType DWord
      New-ItemProperty -Path $path -Name ShowSuperHidden -Value "1" -PropertyType DWord
      reg unload HKLM\DefaultUser