---
- name: features | Installing AD Domain Services
  win_feature: 
    name: 
      - RSAT-AD-AdminCenter
      - AD-Domain-Services
      - DNS
    include_management_tools: yes
    include_sub_features: yes
    state: present
  register: feature_check

- name: Configure static IP address
  win_shell: |
    New-NetIPAddress –IPAddress {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} -DefaultGateway {{ hostvars[inventory_hostname]['ansible_default_ipv4']['gateway'] }} -PrefixLength {{ hostvars[inventory_hostname]['ansible_default_ipv4']['netmask'] }} -InterfaceIndex (Get-NetAdapter).InterfaceIndex

- name: Reboot to complete feature setup and computer name change
  win_reboot:
    pre_reboot_delay: 120
    reboot_timeout: 600
    post_reboot_delay: 120

- name: Check for xDnsServer Powershell module
  win_psmodule:
    name: xDnsServer
    state: present

- name: Configure DNS Forwarders
  win_dsc:
    resource_name: xDnsServerSetting
    Name: DNSServerProperties
    NoRecursion: false
    Forwarders: "{{ windows_domain_info['dns_forward_lookup'] }}"

- name: Set DNS server
  win_dns_client:
    adapter_names: "*"
    ipv4_addresses: "127.0.0.1"

# Provision forest using DSC
- name: Add xActiveDirectory
  win_psmodule:
    name: xActiveDirectory
    state: present

- name: Configure xADDomain Powershell DSC
  win_dsc:
    resource_name: xADDomain
    DomainName: "{{ windows_domain_controller_info['dns_domain_name'] }}"
    DomainAdministratorCredential_username: "{{ windows_domain_controller_info['domain_admin_user'] }}"
    DomainAdministratorCredential_password: "{{ windows_domain_controller_info['domain_admin_password'] }}"
    SafemodeAdministratorPassword_username: "{{ windows_domain_controller_info['safe_mode_username'] }}"
    SafemodeAdministratorPassword_password: "{{ windows_domain_controller_info['safe_mode_password'] }}"

- name: Wait for forest xWaitForADDomain
  win_dsc:
    resource_name: xWaitForADDomain
    DomainName: "{{ windows_domain_controller_info['dns_domain_name'] }}"
    DomainUserCredential_username: "{{ windows_domain_controller_info['domain_admin_user'] }}"
    DomainUserCredential_password: "{{ windows_domain_controller_info['domain_admin_password'] }}"
    RetryCount: 100
    RetryIntervalSec: 5

- name: Reboot to complete domain controller setup (as required)
  win_reboot:
    pre_reboot_delay: 120
    reboot_timeout: 600
    post_reboot_delay: 120 # your mileage may vary

- name: Wait for forest xWaitForADDomain
  win_dsc:
    resource_name: xWaitForADDomain
    DomainName: "{{ windows_domain_controller_info['dns_domain_name'] }}"
    DomainUserCredential_username: "{{ windows_domain_controller_info['domain_admin_user'] }}"
    DomainUserCredential_password: "{{ windows_domain_controller_info['domain_admin_password'] }}"
    RetryCount: 100
    RetryIntervalSec: 5
