---
- name: Check for xDnsServer Powershell module
  win_psmodule:
    name: xDnsServer
    state: present

- name: Setting local DNS Servers
  win_dns_client:
    adapter_names: "*"
    ipv4_addresses: "127.0.0.1"

- name: Configure DNS Forwarders
  win_dsc:
    resource_name: xDnsServerSetting
    Name: DNSServerProperties
    NoRecursion: false
    Forwarders: "{{ windows_domain_info['dns_forward_lookup'] }}"

- name: Configure A Records
  win_dsc:
    resource_name: xDnsRecord
    Name: "{{ item.dns_name }}"
    Target: "{{ item.ip_address }}"
    Zone: "{{ windows_domain_controller_info['dns_domain_name'] }}"
    Type: "ARecord"
    Ensure: "Present"
  with_items: "{{ windows_dns_records }}"