#########################################
# EXAMPLE DEPLOYMENT
#########################################

- hosts: local
  tasks:

#########################################
# DOMAIN CONTROLLER
#########################################

- hosts: all
  vars_files:
    - ../vars/vars.yml 
  gather_facts: True
  environment:
  pre_tasks:
  post_tasks:
  tasks:
    - name: Request and export required certificates from the CA
      include_role:
        name: '{{ rolevar }}'
      loop:
        - 'win_certreq'
      loop_control:
        loop_var: rolevar
      when: inventory_hostname in groups['certificate_authority']

    - name: Prep the certificates for use in splunk
      include_role:
        name: '{{ rolevar }}'
      loop:
        - 'cert_prep'
      loop_control:
        loop_var: rolevar
      when: inventory_hostname in groups['local']

    - name: Stage the certificates for use in splunk
      include_role:
        name: '{{ rolevar }}'
      loop:
        - 'cert_distribute'
      loop_control:
        loop_var: rolevar
      when: ((groups.linux is defined and inventory_hostname in groups['linux']) or (groups.kali is defined and inventory_hostname in groups['kali']) or ((groups.splunk is defined) and inventory_hostname in groups['splunk'])) and not inventory_hostname in groups['windows']