---
    - hosts: domain_controller
      tasks:
        - name: Add PSGallery as Trusted Powershell Repo
          win_shell: |
            if ($false -eq (get-packagesource | Where-Object { $_.Name -eq "PSGallery" } | % { $_.istrusted })){ 
              Set-PackageSource -Name PSGallery -Trusted -Force 
            }