#########################################
# EXAMPLE DEPLOYMENT
#########################################

- hosts: local
  tasks:

#########################################
# DISTRIBUTE CERT
#########################################

- hosts: all
  vars_files:
    - ../vars/vars.yml 
  gather_facts: True
  environment:
  pre_tasks:
  post_tasks:
  tasks:

    # stage certificates on servers
    - name: Stage the certificates for use in splunk
      include_role:
        name: '{{ rolevar }}'
      loop:
        - 'cert_distribute'
      loop_control:
        loop_var: rolevar
      when: inventory_hostname in groups['splunk']
   
  