#########################################
# EXAMPLE DEPLOYMENT
#########################################

- hosts: local
  tasks:

#########################################
# DOMAIN CONTROLLER
#########################################

- hosts: all
  vars_files:
    - ../vars/vars.yml
  gather_facts: true
  environment:
  pre_tasks:
  post_tasks:
  tasks:
    - name: Run windows event forwarder policy setup
      include_role:
        name: '{{ rolevar }}'
      loop:
        - 'win_wef_policy'
      loop_control:
        loop_var: rolevar
      when: groups.domain_controller is defined and inventory_hostname in groups['domain_controller']
