#########################################
# EXAMPLE DEPLOYMENT
#########################################

- hosts: local
  tasks:

#########################################
# DOMAIN CONTROLLER
#########################################

- hosts: all
  vars_files:
    - ../vars/vars.yml 
  gather_facts: True
  environment:
  pre_tasks:
  post_tasks:
  tasks:
    - name: Run windows event forwarder setup
      include_role:
        name: '{{ rolevar }}'
      loop:
        - 'win_member'
      loop_control:
        loop_var: rolevar
      when: groups.member_server is defined and inventory_hostname in groups['member_server']