#########################################
# EXAMPLE DEPLOYMENT
#########################################

- hosts: local
  tasks:

#########################################
# ANSIBLE COMMON
#########################################

- hosts: all:!local
  tasks:
    - name: Apply ansible base configuration (e.g. ssh key scan)
      include_role:
        name: ../roles/ansible_common

#########################################
# DOMAIN CONTROLLER
#########################################

- hosts: all
  vars_files:
    - ../vars/vars.yml
  gather_facts: true
  environment:
  pre_tasks:
    # splunk universal forwarder variables
    - name: Universal Forwarder Variable
      include_vars: ../vars/splunk_universal_forwarder.yml
      when:
        - groups.splunk_universal_forwarder is defined and inventory_hostname in groups['splunk_universal_forwarder']
  post_tasks:
  tasks:
    # all
    - name: Deploy common tasks to all
      include_role:
        name: ../roles/common

    # certificate_authority group only
    - name: Windows Domain
      include_role:
        name: '{{ rolevar }}'
      loop:
        - 'win_dc'
      loop_control:
        loop_var: rolevar
      when: groups.domain_controller is defined and inventory_hostname in groups['domain_controller']
