#########################################
# EXAMPLE DEPLOYMENT
#########################################

- hosts: local
  tasks:

#########################################
# DOMAIN CONTROLLER
#########################################

- hosts: all
  vars_files:
    - ../vars/vars.yml 
  gather_facts: True
  environment:
  pre_tasks:
  post_tasks:
  tasks:
    # all
    - name: Deploy common tasks to all
      include_role:
        name: ../roles/common

    - name: Windows Domain Controllers Setup
      include_role:
        name: '{{ rolevar }}'
      loop:
        - 'win_dc'
        - 'win_dns'
      when: inventory_hostname in groups['domain_controller']

    # certificate_authority group only
    - name: Windows Enterprise PKI
      include_role:
        name: '{{ rolevar }}'
      loop:
        - 'win_ca'
      loop_control:
        loop_var: rolevar
      when: inventory_hostname in groups['certificate_authority']

    # domain_controller group only
    - name: Windows Member Server
      include_role:
        name: '{{ rolevar }}'
      loop:
        - 'win_member'
      loop_control:
        loop_var: rolevar
      when: inventory_hostname in groups['member_server']

    # request certificates
    - name: Request and export required certificates from the CA
      include_role:
        name: '{{ rolevar }}'
      loop:
        - 'win_certreq'
      loop_control:
        loop_var: rolevar
      when: inventory_hostname in groups['certificate_authority']

    # prepare the certificates for splunk
    - name: Prep the certificates for use in splunk
      include_role:
        name: '{{ rolevar }}'
      loop:
        - 'cert_prep'
      loop_control:
        loop_var: rolevar
      when: inventory_hostname in groups['local']

    # stage certificates on servers
    - name: Stage the certificates for use in splunk
      include_role:
        name: '{{ rolevar }}'
      loop:
        - 'cert_distribute'
      loop_control:
        loop_var: rolevar
      when: inventory_hostname in groups['splunk']

   
  