---
ca_path_debian: /usr/local/share/ca-certificates
ca_path:
    RedHat:
        6: /usr/local/share/ca-certificates
        7: /etc/pki/ca-trust/source/anchors
        8: /etc/pki/ca-trust/source/anchors
    Debian:
        7: '{{ ca_path_debian }}'
        8: '{{ ca_path_debian }}'
        9: '{{ ca_path_debian }}'
        10: '{{ ca_path_debian }}'
    Kali GNU/Linux:
        2019: '{{ ca_path_debian }}'
        2020: '{{ ca_path_debian }}'
