---
- name: Check for xDnsServer xActiveDirectory Powershell modules
  win_shell: |
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    Set-PackageSource -Name PSGallery -Trusted -Force 
    Install-Module -Name xActiveDirectory
    Install-Module -Name xComputerManagement

- name: Force Allow Powershell Unrestricted Execution (required for xWaitForADDomain on Windows 10)
  win_shell: |
    Set-Executionpolicy -ExecutionPolicy Unrestricted -Force -Scope LocalMachine
  when: ansible_os_name is search("Microsoft Windows 10")

- name: Fix start menu for "administrator" account on the domain
  win_shell: |
    New-ItemProperty -Path HKLM:Software\Microsoft\Windows\CurrentVersion\policies\system -Name FilterAdministratorToken -PropertyType DWord -Value 1 -Force 
  when: ansible_os_name is search("Microsoft Windows 10")
    
- name: Fix desktop background double print
  win_shell: |
    Remove-Item 'C:\Users\Default\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\RunWallpaperSetupInit.cmd'
  ignore_errors: yes
  when: ansible_os_name is search("Microsoft Windows 10")

- name: Setting DNS Servers
  win_shell: |
    Set-DnsClientServerAddress -InterfaceAlias 'Ethernet*' -ServerAddresses "{{ windows_domain_info['dns_servers'] }}"
  register: script_result

- name: Script result
  debug:
    msg:
      - "{{ script_result }}"

# wait for domain to be available
- name: Wait for forest xWaitForADDomain
  win_dsc:
    resource_name: xWaitForADDomain
    DomainName: "{{ windows_domain_controller_info['dns_domain_name'] }}"
    DomainUserCredential_username: "{{ windows_domain_controller_info['domain_admin_user'] }}"
    DomainUserCredential_password: "{{ windows_domain_controller_info['domain_admin_password'] }}"
    RetryCount: 100
    RetryIntervalSec: 5

- name: Join to the domain using xComputer
  win_dsc:
    resource_name: xComputer
    Name: "{{ inventory_hostname.split('.')[0] | lower }}"
    DomainName: "{{ windows_domain_controller_info['dns_domain_name'] }}"
    Credential_username: "{{ windows_domain_controller_info['domain_admin_user'] }}"
    Credential_password: "{{ windows_domain_controller_info['domain_admin_password'] }}"
    #JoinOu: "{{ join_domain_default_dn_base }}"
  register: join_domain

# migrate to domain user
- name: Set ansible user for role
  set_fact:
    ansible_ssh_user: "{{ windows_domain_controller_info.domain_admin_user }}"
    ansible_ssh_pass: "{{ windows_domain_controller_info.domain_admin_password }}"
    ansible_winrm_transport: ntlm
  no_log: true

- name: Reboot to complete domain membership
  include: restart_windows.yml