---
# Set static IP
- name: Configure static IP address
  win_shell: |
    Set-DnsClientGlobalSetting -SuffixSearchList @("{{ windows_domain_controller_info['dns_domain_name'] }}")
    function INT64-toIP() {   
      param ([int64]$int)   
      return (([math]::truncate($int/16777216)).tostring()+"."+([math]::truncate(($int%16777216)/65536)).tostring()+"."+([math]::truncate(($int%65536)/256)).tostring()+"."+([math]::truncate($int%256)).tostring() )  
    }

    $adapter = get-netadapter
    $interface = Get-NetIPAddress -AddressFamily IPv4 -InterfaceIndex $adapter.InterfaceIndex
    Disable-NetAdapterBinding –InterfaceAlias 'Ethernet*' –ComponentID ms_tcpip6
    $gateway = get-netroute -DestinationPrefix '0.0.0.0/0' | select -ExpandProperty NextHop
    $mask = [Net.IPAddress]::Parse((INT64-toIP -int ([convert]::ToInt64(("1"*$interface.PrefixLength+"0"*(32-$interface.PrefixLength)),2))))

    $index = $adapter.InterfaceIndex
    $NetInterface = Get-WmiObject Win32_NetworkAdapterConfiguration | where {$_.InterfaceIndex -eq $index}
    $NetInterface.EnableStatic($interface.IPAddress, $mask)
    $NetInterface.SetGateways($gateway) 
  async: 30
  poll: 0

- name: Wait for the interface change to complete
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 120
    timeout: 300

- name: Display DNS server IP
  debug:
    msg:
      - "Setting DNS Server: {{ windows_domain_info }}"

- name: Setting DNS Servers
  win_shell: |
    Set-DnsClientServerAddress -InterfaceAlias 'Ethernet*' -ServerAddresses "{{ windows_domain_info['dns_forward_lookup'] | join('","') }}"
  register: script_result

- name: Script result
  debug:
    msg:
      - "{{ script_result }}"

- name: Reboot to complete computer name change
  debug:
    msg: "Rebooting..."
  notify: Restart windows
  changed_when: true