---
- name: Set DNS server
  win_shell: |
    Set-DnsClientServerAddress -InterfaceAlias 'Ethernet*' -ServerAddresses "127.0.0.1"
  register: script_result

- name: Script result
  debug:
    msg:
      - "{{ script_result }}"

- name: Configure xADDomain Powershell DSC
  win_dsc:
    resource_name: xADDomain
    DomainName: "{{ windows_domain_controller_info['dns_domain_name'] }}"
    DomainNetbiosName: "{{ windows_domain_controller_info['domain_netbios_name'] }}"
    DomainAdministratorCredential_username: "{{ windows_domain_controller_info['domain_admin_user'] }}"
    DomainAdministratorCredential_password: "{{ windows_domain_controller_info['domain_admin_password'] }}"
    SafemodeAdministratorPassword_username: "{{ windows_domain_controller_info['safe_mode_username'] }}"
    SafemodeAdministratorPassword_password: "{{ windows_domain_controller_info['safe_mode_password'] }}"

- name: Display current winrm transport
  debug:
    msg:
      - "ansible_winrm_transport: {{ ansible_winrm_transport }}"

# in addition to requiring winrm http listener being enable, basic auth is required after promotion
- name: Force winrm auth type to basic
  set_fact:
    temp_winrm_transport: "{{ ansible_winrm_transport }}"
    ansible_winrm_transport: basic

- name: Display modified winrm transport
  debug:
    msg:
      - "ansible_winrm_transport: {{ ansible_winrm_transport }}"
      - "temp_winrm_transport: {{ temp_winrm_transport }}"

- name: Reset winrm to post promo config
  set_fact:
    ansible_winrm_transport: "{{ temp_winrm_transport }}"

- name: Reboot to complete domain controller setup (as required)
  include: restart_windows.yml

