---
- name: Set ansible user for role
  set_fact:
    ansible_ssh_user: "{{ windows_domain_controller_info.domain_admin_user }}"
    ansible_ssh_pass: "{{ windows_domain_controller_info.domain_admin_password }}"
    ansible_winrm_transport: ntlm
  no_log: true

- name: Stage CAPolicy.inf
  template: 
    src: ../template/capolicy.inf.j2
    dest: c:\windows\CAPolicy.inf

- name: Create PKI Virtual Directory
  win_shell: |
    $path = "c:\pki"
    $share = Get-SmbShare -Name "pki" -ErrorAction SilentlyContinue

    # remove share if exists
    if($share -ne $null){
        write-output "Removing existing share"
        Remove-SmbShare -Name "pki" -Force
    }

    # remove directory if exists
    if([System.IO.Directory]::Exists($path)){
        write-output "Removing existing directory"
        Remove-Item $path -Recurse -Force
    }

    # create directory and share
    New-item -path $path –type directory
    Write-Output "Example CPS statement" | Out-File $path\cps.txt
    New-SMBShare -Name pki $path -FullAccess SYSTEM,"{{ windows_domain_controller_info['domain_netbios_name'] }}\Domain Admins" -ChangeAccess "{{ windows_domain_controller_info['domain_netbios_name'] }}\Cert Publishers"

- name: Install ADCS with sub features and management tools
  win_feature:
    name: 
      - Adcs-Cert-Authority
      - Adcs-Enroll-Web-Pol
    state: present
    include_management_tools: yes
  register: windows_adcs

- name: Reboot if installing Adcs-Cert-Authority feature requires it
  include: restart_windows.yml
  when: windows_adcs.reboot_required

- name: Add PSGallery as Trusted Powershell Repo
  win_shell: |
    if ($false -eq (get-packagesource | Where-Object { $_.Name -eq "PSGallery" } | % { $_.istrusted })){ 
      Set-PackageSource -Name PSGallery -Trusted -Force 
    }

# Add powershell modules
- name: Check for xDnsServer Powershell module
  win_shell: |
    Install-Module -Name xDnsServer

# add pki dns cname
- name: Configure pki CNAME
  win_dsc:
    resource_name: xDnsRecord
    Name: "pki"
    Zone: "{{ windows_domain_controller_info['dns_domain_name'] }}"
    Target: "{{ groups['domain_controller'][0].split('.')[0] | lower }}.{{ windows_domain_controller_info['dns_domain_name'] }}"
    Type: CName

# add iis virtual directory
- name: Add PKI Virtual Directory
  win_shell: |
    Import-Module WebAdministration
    $FolderPath = "c:\pki"
    New-WebVirtualDirectory -Site "Default Web Site" -Name "pki" -PhysicalPath $FolderPath
    $apppoolsid = (Get-ItemProperty IIS:\AppPools\DefaultAppPool).applicationPoolSid
    $acl = Get-Acl $FolderPath
    $colRights = [System.Security.AccessControl.FileSystemRights]"Read,ExecuteFile,ListDirectory"
    $permission = "IIS AppPool\DefaultAppPool",$colRights,"ContainerInherit,ObjectInherit","None","Allow"
    $accessRule = New-Object System.Security.AccessControl.FileSystemAccessRule $permission  
    $acl.AddAccessRule($accessRule) 
    $acl | Set-Acl $FolderPath

- name: Add ActiveDirectoryCSDsc
  win_shell: |
    Install-Module -Name ActiveDirectoryCSDsc

- name: Configure ActiveDirectoryCSDsc Powershell DSC
  win_dsc:
    resource_name: DSC_AdcsCertificationAuthority
    IsSingleInstance: 'Yes'
    CAType: 'EnterpriseRootCA'
    CryptoProviderName: 'RSA#Microsoft Software Key Storage Provider'
    CACommonName: "{{ windows_certificate_authority_info['CACommonName'] }}"
    Ensure: 'Present'
    KeyLength: "{{ windows_certificate_authority_info['KeyLength'] }}"
    HashAlgorithmName: "{{ windows_certificate_authority_info['HashAlgorithmName'] }}"
    ValidityPeriod: "{{ windows_certificate_authority_info['ValidityPeriod'] }}"
    ValidityPeriodUnits: "{{ windows_certificate_authority_info['ValidityPeriodUnits'] }}"
    PsDscRunAsCredential_username: "{{ windows_domain_controller_info['domain_admin_user'] }}"
    PsDscRunAsCredential_password: "{{ windows_domain_controller_info['domain_admin_password'] }}"
    Credential_username: "{{ windows_domain_controller_info['domain_admin_user'] }}"
    Credential_password: "{{ windows_domain_controller_info['domain_admin_password'] }}"

# add crl extension
- name: Add CRL Extension
  win_shell: |
    $crllist = Get-CACrlDistributionPoint; 
    foreach ($crl in $crllist) {
      Remove-CACrlDistributionPoint $crl.uri -Force
    }; 
    Add-CACRLDistributionPoint -Uri C:\Windows\System32\CertSrv\CertEnroll\%3%8%9.crl -PublishToServer -PublishDeltaToServer -Force
    Add-CACRLDistributionPoint -Uri http://pki.{{ windows_domain_controller_info['dns_domain_name'] }}/pki/%3%8%9.crl -AddToCertificateCDP -Force
    Add-CACRLDistributionPoint -Uri file://\\{{ groups['domain_controller'][0].split('.')[0] | lower }}.{{ windows_domain_controller_info['dns_domain_name'] }}\pki\%3%8%9.crl -PublishToServer -PublishDeltaToServer -Force
    restart-service certsvc

- name: Add AIA Extension
  win_shell: |
    $aialist = Get-CAAuthorityInformationAccess; 
    foreach ($aia in $aialist) {
      Remove-CAAuthorityInformationAccess $aia.uri -Force
    }; 
    Add-CAAuthorityInformationAccess -AddToCertificateAia http://pki.{{ windows_domain_controller_info['dns_domain_name'] }}/pki/%1_%3%4.crt -Force
    restart-service certsvc 

- name: Copy crt and crl to pki directory
  win_shell: |
    Copy-Item C:\Windows\system32\certsrv\certenroll\*.cr* \\localhost\pki

- name: Configure Client-Server Authentication and IAS RAS Server Templates for Autoenroll
  win_shell: |
    Function newOid {
      param ($ConfigContext)
      $Hex = '0123456789ABCDEF'
      do {
          $oid = [ADSI]"LDAP://CN=OID,CN=Public Key Services,CN=Services,$ConfigContext" 
          $oidforest = $oid.'msPKI-Cert-Template-OID'
          $oid1 = Get-Random -Minimum 1000000  -Maximum 99999999
          $oid2 = Get-Random -Minimum 10000000 -Maximum 99999999
          $oid3 = $null
          For ($i=1;$i -le 32;$i++) {$oid3 += $Hex.Substring((Get-Random -Minimum 0 -Maximum 16),1)}
          $Name = "$oid2.$oid3"
          $msPKICertTemplateOID = "$oidforest.$oid1.$oid2"
      } until (($($oid.psbase.children | where { $_.cn -eq $Name -and $_.'msPKI-Cert-Template-OID' -eq $msPKICertTemplateOID }).Count -eq 0))
      Return @{
          oid  = $msPKICertTemplateOID
          name = $Name
      }
    }
    Function addTemplateAcl{
    param($Template, $User, $Read, $Enroll, $AutoEnroll)
        $user = New-Object System.Security.Principal.NTAccount($User)
        $enrollGuid = [GUID]'0e10c968-78fb-11d2-90d4-00c04f79dc55'
        $autoenrollGuid = [GUID]'a05b8cc2-17bc-4802-a710-e7c15ab866a2'
        $readGuid = [System.DirectoryServices.ActiveDirectoryRights] "GenericRead"
        $inheritedType = [GUID]'00000000-0000-0000-0000-000000000000'
        $allow = [System.Security.AccessControl.AccessControlType]"Allow"
        if($Enroll) { $Template.ObjectSecurity.AddAccessRule((New-Object System.DirectoryServices.ActiveDirectoryAccessRule $user, 'ExtendedRight', $allow, $enrollGuid, 'None', $inheritedType)) }
        if($AutoEnroll) { $Template.ObjectSecurity.AddAccessRule((New-Object System.DirectoryServices.ActiveDirectoryAccessRule $user, 'ExtendedRight', $allow, $autoenrollGuid, 'None', $inheritedType)) }
        if($Read) { $Template.ObjectSecurity.AddAccessRule((New-Object System.DirectoryServices.ActiveDirectoryAccessRule $user, $readGuid, $allow, $inheritedType)) }
        $Template.commitchanges()

        return @{
            Template = $Template
        }
    }
    Function copyTemplate{
    param($NewTemplateName, $SourceTemplateName, $ConfigContext)
        $ADSI = [ADSI]"LDAP://CN=Certificate Templates,CN=Public Key Services,CN=Services,$ConfigContext"
        $st = $ADSI.psbase.children | where {$_.displayName -eq $SourceTemplateName}
        $oid = newOid -ConfigContext $ConfigContext
        $t = $ADSI.Create("pKICertificateTemplate", ("CN={0}" -f $oid.name)) 
        $t.put("distinguishedName",("CN={0},CN=Certificate Templates,CN=Public Key Services,CN=Services,{1}" -f $oid.name,$ConfigContext))         
        $t.put("flags","131680")
        $t.put("displayName",$NewTemplateName)
        $t.put("revision","100")
        $t.put("pKIDefaultKeySpec","1")
        $t.SetInfo()
        $t.put("pKIMaxIssuingDepth","0")
        $t.put("pKIDefaultCSPs","1,Microsoft RSA SChannel Cryptographic Provider")
        $t.put("msPKI-RA-Signature","0")
        $t.put("msPKI-Minimal-Key-Size","2048")
        $t.put("msPKI-Template-Schema-Version","2")
        $t.put("msPKI-Template-Minor-Revision","0")
        $t.put("msPKI-Cert-Template-OID",$oid.oid)
        $t.putex(3,"msPKI-Certificate-Application-Policy",@("1.3.6.1.5.5.7.3.1","1.3.6.1.5.5.7.3.2"))
        $t.SetInfo()
        $t.ObjectSecurity.SetAccessRuleProtection($st.ObjectSecurity.AreAccessRulesProtected, $false)
        $t.ObjectSecurity.Access | % {
            $t.ObjectSecurity.RemoveAccessRule($_)
        }
        $t.commitchanges()
        $st.ObjectSecurity.Access | % {
            $t.ObjectSecurity.AddAccessRule($_)
        }
        $t.commitchanges()
        $t.pKIKeyUsage = $st.pKIKeyUsage
        $t.pKIExpirationPeriod = $st.pKIExpirationPeriod
        $t.pKIOverlapPeriod = $st.pKIOverlapPeriod
        $t.SetInfo()

        return @{
            Template = $t
        }
    }
    Function publishTemplate{
    param($Template, $ConfigContext)
        $adsi = [ADSI]"LDAP://CN=Enrollment Services,CN=Public Key Services,CN=Services,$ConfigContext"
        $adsi.psbase.children | % { 
            $_.putex(3,'certificateTemplates',@($Template.Name))
            $_.commitchanges()
        }
    }

    $cc = ([ADSI]"LDAP://RootDSE").ConfigurationNamingContext 
    $t = copyTemplate -NewTemplateName "Web Server Policy" -SourceTemplateName "Web Server" -ConfigContext $cc
    $t.Template.putex(3,"pKICriticalExtensions",@("2.5.29.7","2.5.29.15"))
    $t.Template.putex(3,"pKIExtendedKeyUsage",@("1.3.6.1.5.5.7.3.1","1.3.6.1.5.5.7.3.2"))
    $t.Template.put("msPKI-Enrollment-Flag","0")
    $t.Template.put("msPKI-Private-Key-Flag","16842752")
    $t.Template.put("msPKI-Certificate-Name-Flag","1")
    $t.Template.SetInfo()
    publishTemplate -Template $t.Template -ConfigContext $cc

    $t = copyTemplate -NewTemplateName "RAS and IAS Server Policy" -SourceTemplateName "RAS and IAS Server" -ConfigContext $cc
    $t.Template.put("pKICriticalExtensions","2.5.29.15")
    $t.Template.putex(3,"pKIExtendedKeyUsage",@("1.3.6.1.5.5.7.3.1","1.3.6.1.5.5.7.3.2"))
    $t.Template.put("msPKI-Enrollment-Flag","32")
    $t.Template.put("msPKI-Private-Key-Flag","0")
    $t.Template.put("msPKI-Certificate-Name-Flag","-2013265920")
    $t.Template.SetInfo()
    $t = addTemplateAcl -Template $t.Template -User "RAS and IAS Servers" -Read $true -Enroll $true -AutoEnroll $true
    publishTemplate -Template $t.Template -ConfigContext $cc

    "Workstation Authentication","Domain Controller Authentication" | % { 
      $t = copyTemplate -NewTemplateName "$_ Policy" -SourceTemplateName $_ -ConfigContext $cc
      $t.Template.put("pKICriticalExtensions",$p)
      $t.Template.putex(3,"pKIExtendedKeyUsage",@("1.3.6.1.5.5.7.3.1","1.3.6.1.5.5.7.3.2"))
      $t.Template.put("msPKI-Enrollment-Flag","32")
      $t.Template.put("msPKI-Private-Key-Flag","67371264")
      $t.Template.put("msPKI-Certificate-Name-Flag","-2013265920")
      $t.Template.SetInfo()
      if($_ -eq "Workstation Authentication") { $t = addTemplateAcl -Template $t.Template -User "Domain Computers" -Read $true -Enroll $true -AutoEnroll $true }
      publishTemplate -Template $t.Template -ConfigContext $cc
    }

    restart-service certsvc