syslog:
    user: splunk
    group: splunk
    config:
        path: "/etc/rsyslog.d/syslog-collector.conf"
    log:
        path: "/var/log/syslog-collector"
    pid:
        path: "/var/run/syslogd.pid"
    service:
        name: "rsyslog"
    logrotate:
        config:
            path: "/etc/logrotate.d/splunk-syslog"
    test:
        - message: "This is a test TCP message"
          port: "514"
          protocol: "tcp"
          destination: "0.0.0.0"
        - message: "This is a test UDP message"
          port: "514"
          protocol: "udp"
          destination: "0.0.0.0"
    